project:
  name: "blog"
  template: "blog"
  title: Demo Blog
  frontend: nextjs_base
  domain: localhost
plugins:
  gdpr:
    enabled: true
  security:
    enabled: true
  analytics:
    enabled: true
